const fs = require('fs');

const venuesFile = 'src/data/venues.ts';
let v = fs.readFileSync(venuesFile, 'utf8');

const newVenues = `
  {
    id: 'v501',
    name: 'Mahanakhon SkyBar',
    slug: 'mahanakhon-skybar',
    description: 'Highest rooftop bar in Bangkok with 360-degree views',
    category: 'bar',
    subcategories: ['rooftop', 'cocktails'],
    city: 'Bangkok',
    citySlug: 'bangkok',
    neighborhood: 'Silom',
    neighborhoodSlug: 'silom',
    address: 'Mahanakhon Building, 76th floor',
    latitude: 13.7276,
    longitude: 100.5296,
    priceRange: 3,
    rating: 4.6,
    reviewCount: 892,
    isVerified: true,
    deals: [],
  },
  {
    id: 'v502',
    name: 'Thonglor Brewing Co',
    slug: 'thonglor-brewing-co',
    description: 'Local craft brewery in the heart of Thonglor',
    category: 'bar',
    subcategories: ['brewery', 'craft-beer'],
    city: 'Bangkok',
    citySlug: 'bangkok',
    neighborhood: 'Thonglor',
    neighborhoodSlug: 'thonglor',
    address: 'Soi Thonglor 9',
    latitude: 13.7302,
    longitude: 100.5826,
    priceRange: 2,
    rating: 4.5,
    reviewCount: 567,
    isVerified: true,
    deals: [],
  },
  {
    id: 'v503',
    name: 'Ekkamai Beer House',
    slug: 'ekkamai-beer-house',
    description: 'Popular craft beer spot in Ekkamai',
    category: 'bar',
    subcategories: ['craft-beer', 'live-music'],
    city: 'Bangkok',
    citySlug: 'bangkok',
    neighborhood: 'Ekkamai',
    neighborhoodSlug: 'ekkamai',
    address: 'Soi Ekkamai 21',
    latitude: 13.7222,
    longitude: 100.5872,
    priceRange: 1,
    rating: 4.2,
    reviewCount: 445,
    isVerified: true,
    deals: [],
  },
  {
    id: 'v504',
    name: 'Vertigo Rooftop Bar',
    slug: 'vertigo-rooftop-bar',
    description: 'Iconic rooftop bar at Banyan Tree Hotel',
    category: 'bar',
    subcategories: ['rooftop', 'fine-dining'],
    city: 'Bangkok',
    citySlug: 'bangkok',
    neighborhood: 'Sathorn',
    neighborhoodSlug: 'sathorn',
    address: 'Banyan Tree Hotel, 61st floor',
    latitude: 13.7223,
    longitude: 100.5365,
    priceRange: 3,
    rating: 4.7,
    reviewCount: 945,
    isVerified: true,
    deals: [],
  },
  {
    id: 'v505',
    name: 'RCA Royal Club',
    slug: 'rca-royal-club',
    description: 'Premier nightclub on the famous RCA strip',
    category: 'bar',
    subcategories: ['nightclub', 'dj'],
    city: 'Bangkok',
    citySlug: 'bangkok',
    neighborhood: 'RCA',
    neighborhoodSlug: 'rca',
    address: 'RCA Plaza',
    latitude: 13.7570,
    longitude: 100.5730,
    priceRange: 2,
    rating: 4.1,
    reviewCount: 789,
    isVerified: true,
    deals: [],
  }
`;

v = v.replace(/\n\]\n\n\/\/ Helper functions/, '\n,' + newVenues.trim() + '\n]\n\n// Helper functions');
fs.writeFileSync(venuesFile, v);
console.log('Added 5 Bangkok venues');
